[
["图片工具","tool","avif-support","OK",""],
["图片工具","tool","background-remover","OK",""],
["图片工具","tool","batch-exif-remover","OK",""],
["图片工具","tool","beauty-editor","OK",""],
["图片工具","tool","bulk-processor","OK",""],
["图片工具","tool","circle-crop","OK",""],
["图片工具","tool","color-palette","OK",""],
["图片工具","tool","compressor","OK",""],
["图片工具","tool","converter","OK",""],
["图片工具","tool","cropper","OK",""],
["图片工具","tool","face-blur","OK",""],
["图片工具","tool","favicon-generator","OK",""],
["图片工具","tool","gif-editor","OK",""],
["图片工具","tool","gif-splitter","OK",""],
["图片工具","tool","heic-converter","OK",""],
["图片工具","tool","heic-to-jpg","OK",""],
["图片工具","tool","ico-icon-generator","OK",""],
["图片工具","tool","id-photo","OK",""],
["图片工具","tool","image-adjust","OK",""],
["图片工具","tool","image-border","OK",""],
["图片工具","tool","image-compare","OK",""],
["图片工具","tool","image-compressor","OK",""],
["图片工具","tool","image-enhancer","OK",""],
["图片工具","tool","image-exif-remover","OK",""],
["图片工具","tool","image-filters","OK",""],
["图片工具","tool","image-flip","OK",""],
["图片工具","tool","image-grayscale","OK",""],
["图片工具","tool","image-merger","OK",""],
["图片工具","tool","image-rotator","BUG","[P] blob is not defined"],
["图片工具","tool","image-shadow","OK",""],
["图片工具","tool","image-splitter","OK",""],
["图片工具","tool","image-upscaler","CDN","[C] Failed to load resource: net::ERR_CONNECTION_RESET"],
["图片工具","tool","meme-generator","OK",""],
["图片工具","tool","metadata-viewer","OK",""],
["图片工具","tool","object-remover","OK",""],
["图片工具","tool","ocr","CDN","[C] Failed to load resource: net::ERR_CONNECTION_RESET"],
["图片工具","tool","photo-map","OK",""],
["图片工具","tool","photo-restoration","OK",""],
["图片工具","tool","print-resizer","OK",""],
["图片工具","tool","product-white-background","CDN","[C] Failed to load resource: net::ERR_CONNECTION_RESET"],
["图片工具","tool","qr-code-generator","OK",""],
["图片工具","tool","resizer","OK",""],
["图片工具","tool","screenshot-to-image","OK",""],
["图片工具","tool","signature-maker","OK","[D] Please draw your signature first."],
["图片工具","tool","social-media-post","OK",""],
["图片工具","tool","svg-to-png","OK",""],
["图片工具","tool","text-on-image","OK",""],
["图片工具","tool","watermark","OK",""],
["PDF工具","tool","csv-to-pdf","OK",""],
["PDF工具","tool","epub-to-pdf","OK",""],
["PDF工具","tool","excel-to-pdf","OK",""],
["PDF工具","tool","html-to-pdf","OK",""],
["PDF工具","tool","image-to-pdf","OK",""],
["PDF工具","tool","pdf-annotate","OK","[C] Failed to load resource: net::ERR_TIMED_OUT"],
["PDF工具","tool","pdf-compare","OK",""],
["PDF工具","tool","pdf-compress","OK","[C] Failed to load resource: net::ERR_CONNECTION_RESET"],
["PDF工具","tool","pdf-crop","OK",""],
["PDF工具","tool","pdf-delete-pages","OK","[D] Enter pages to delete."],
["PDF工具","tool","pdf-editor","OK",""],
["PDF工具","tool","pdf-extract-pages","OK","[D] Enter pages to extract."],
["PDF工具","tool","pdf-merge","OK",""],
["PDF工具","tool","pdf-number-pages","OK",""],
["PDF工具","tool","pdf-organize","OK",""],
["PDF工具","tool","pdf-redact","OK",""],
["PDF工具","tool","pdf-rotate","OK","[C] Failed to load resource: net::ERR_CONNECTION_CLOSED"],
["PDF工具","tool","pdf-split","OK",""],
["PDF工具","tool","pdf-to-excel","OK",""],
["PDF工具","tool","pdf-to-image","OK",""],
["PDF工具","tool","pdf-to-ppt","OK",""],
["PDF工具","tool","pdf-to-word","OK",""],
["PDF工具","tool","txt-to-pdf","OK",""],
["PDF工具","tool","word-to-pdf","OK",""],
["视频工具","tool","video-compressor","OK",""],
["视频工具","tool","video-crop","OK",""],
["视频工具","tool","video-rotate","OK",""],
["视频工具","tool","video-speed","OK",""],
["视频工具","tool","video-to-frames","OK",""],
["视频工具","tool","video-to-gif","OK",""],
["视频工具","tool","video-to-mp3","OK",""],
["文本工具","tool","base64","OK",""],
["文本工具","tool","case-converter","OK",""],
["文本工具","tool","html-encoder","OK",""],
["文本工具","tool","json-formatter","OK",""],
["文本工具","tool","password-generator","OK",""],
["文本工具","tool","regex-tester","OK",""],
["文本工具","tool","text-diff","OK",""],
["文本工具","tool","text-find-replace","OK",""],
["文本工具","tool","text-sorter","OK",""],
["文本工具","tool","url-encoder","OK",""],
["文本工具","tool","uuid-generator","OK",""],
["文本工具","tool","word-counter","OK",""],
["工作流","workflow","ai-background-studio","OK",""],
["工作流","workflow","amazon-listing-suite","OK",""],
["工作流","workflow","app-store-screenshot-suite","OK",""],
["工作流","workflow","avatar-pipeline","OK",""],
["工作流","workflow","batch-watermark-protect","OK",""],
["工作流","workflow","before-after-comparison","BUG","[P] Identifier \'a\' has already been declared"],
["工作流","workflow","blog-image-pack","OK",""],
["工作流","workflow","circular-avatar-cropper","OK",""],
["工作流","workflow","color-palette-extractor","MIN","[P] Failed to execute \'writeText\' on \'Clipboard\': Write permission denied."],
["工作流","workflow","course-tutorial-pack","OK",""],
["工作流","workflow","design-slicer","OK",""],
["工作流","workflow","duplicate-image-finder","OK",""],
["工作流","workflow","e-commerce-pack","OK",""],
["工作流","workflow","email-signature-pack","OK",""],
["工作流","workflow","etsy-seller-photo-pack","OK",""],
["工作流","workflow","event-photography-bundle","OK",""],
["工作流","workflow","exif-metadata-remover","OK",""],
["工作流","workflow","food-photography-bundle","OK",""],
["工作流","workflow","freelancer-portfolio-pack","OK",""],
["工作流","workflow","gif-maker","BUG","[P] Failed to construct \'Worker\': Script at \'https://cdnjs.cloudflare.com/ajax/libs/gif.js/0.2.0/gif.worker.js\' cann"],
["工作流","workflow","instagram-grid-splitter","OK",""],
["工作流","workflow","listing-image-suite","OK",""],
["工作流","workflow","long-screenshot-stitcher","OK",""],
["工作流","workflow","passport-photo-maker","OK",""],
["工作流","workflow","pdf-to-images","CDN","[P] InvalidPDFException"],
["工作流","workflow","phone-wallpaper-generator","OK",""],
["工作流","workflow","pinterest-pin-maker","OK",""],
["工作流","workflow","podcast-cover-suite","OK",""],
["工作流","workflow","print-ready-prep","OK",""],
["工作流","workflow","product-image-optimizer","OK",""],
["工作流","workflow","real-estate-photo-pack","OK",""],
["工作流","workflow","resume-cv-photo","OK",""],
["工作流","workflow","screenshot-beautifier","OK",""],
["工作流","workflow","social-media-kit","OK",""],
["工作流","workflow","website-image-optimizer","OK",""],
["工作流","workflow","youtube-thumbnail-suite","OK",""]
]